name: randomly-delete-message

services:
  bot:
    image: summerwya/randomly-delete-message:latest
    build:
      context: .
    restart: on-failure
    environment:
      CHANCE: 30
      DISCORD_BOT_TOKEN: "your token here"